In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

digits = load_digits()

import warnings
warnings.filterwarnings('ignore')

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.30)

In [36]:
# Logistic regression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [37]:
## SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [38]:
# Random Frorest 

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [39]:
# KFold

from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [40]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [41]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [42]:
get_score(RandomForestClassifier(), X_train,X_test, y_train, y_test)

0.9722222222222222

In [43]:
# StratifiedFold

from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [50]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in fold.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test =  digits.data[train_index], digits.data[test_index],\
                                        digits.target[train_index], digits.target[test_index]
    
    score_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [51]:
score_l

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [52]:
score_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [53]:
score_rf

[0.9398998330550918, 0.9382303839732888, 0.9115191986644408]

In [54]:
from sklearn.model_selection import cross_val_score

In [58]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [59]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [60]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93611111, 0.89444444, 0.95543175, 0.95821727, 0.91086351])